server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-15-164-49-247.ap-northeast-2.compute.amazonaws.com:3306/ohgiraffers_db?serverTimezone=Asia/Seoul
    username: ohgiraffers
    password: ohgiraffers

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
